# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_emailreportroad.ui'
#
# Created: Tue Jul 22 16:39:09 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
class emailReportRoadDialog(QtGui.QDialog):
    def __init__(self):
        QtGui.QDialog.__init__(self)
	self.uiEmailR = Ui_emailReportRoad()
        self.uiEmailR.setupUi(self)
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_emailReportRoad(object):
    def setupUi(self, emailReportRoad):
        emailReportRoad.setObjectName(_fromUtf8("emailReportRoad"))
        emailReportRoad.resize(711, 582)
        self.label = QtGui.QLabel(emailReportRoad)
        self.label.setGeometry(QtCore.QRect(50, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(emailReportRoad)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(emailReportRoad)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(emailReportRoad)
        self.label_4.setGeometry(QtCore.QRect(50, 360, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(emailReportRoad)
        self.label_5.setGeometry(QtCore.QRect(50, 400, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txtUsernameRep = QtGui.QLineEdit(emailReportRoad)
        self.txtUsernameRep.setGeometry(QtCore.QRect(200, 200, 451, 31))
        self.txtUsernameRep.setObjectName(_fromUtf8("txtUsernameRep"))
        self.txtPasswordRep = QtGui.QLineEdit(emailReportRoad)
        self.txtPasswordRep.setGeometry(QtCore.QRect(200, 240, 451, 31))
        self.txtPasswordRep.setObjectName(_fromUtf8("txtPasswordRep"))
        self.txtFromRep = QtGui.QLineEdit(emailReportRoad)
        self.txtFromRep.setGeometry(QtCore.QRect(200, 320, 451, 31))
        self.txtFromRep.setObjectName(_fromUtf8("txtFromRep"))
        self.txtToRep = QtGui.QLineEdit(emailReportRoad)
        self.txtToRep.setGeometry(QtCore.QRect(200, 360, 451, 31))
        self.txtToRep.setObjectName(_fromUtf8("txtToRep"))
        self.txtSubjectRep = QtGui.QLineEdit(emailReportRoad)
        self.txtSubjectRep.setGeometry(QtCore.QRect(200, 400, 451, 31))
        self.txtSubjectRep.setObjectName(_fromUtf8("txtSubjectRep"))
        self.label_6 = QtGui.QLabel(emailReportRoad)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(emailReportRoad)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(emailReportRoad)
        self.label_8.setGeometry(QtCore.QRect(50, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lblReportAttached = QtGui.QLabel(emailReportRoad)
        self.lblReportAttached.setGeometry(QtCore.QRect(200, 450, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblReportAttached.setFont(font)
        self.lblReportAttached.setObjectName(_fromUtf8("lblReportAttached"))
        self.label_9 = QtGui.QLabel(emailReportRoad)
        self.label_9.setGeometry(QtCore.QRect(20, 280, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnSendEmailRoad = QtGui.QPushButton(emailReportRoad)
        self.btnSendEmailRoad.setGeometry(QtCore.QRect(310, 500, 98, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnSendEmailRoad.setFont(font)
        self.btnSendEmailRoad.setStyleSheet(_fromUtf8(""))
        self.btnSendEmailRoad.setObjectName(_fromUtf8("btnSendEmailRoad"))
        self.btnEmailClear = QtGui.QPushButton(emailReportRoad)
        self.btnEmailClear.setGeometry(QtCore.QRect(430, 500, 98, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnEmailClear.setFont(font)
        self.btnEmailClear.setObjectName(_fromUtf8("btnEmailClear"))
        self.btnEmailExit = QtGui.QPushButton(emailReportRoad)
        self.btnEmailExit.setGeometry(QtCore.QRect(550, 500, 98, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnEmailExit.setFont(font)
        self.btnEmailExit.setObjectName(_fromUtf8("btnEmailExit"))
        self.lblRepAttachedOk = QtGui.QLabel(emailReportRoad)
        self.lblRepAttachedOk.setGeometry(QtCore.QRect(660, 450, 31, 31))
        self.lblRepAttachedOk.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/yes.png);"))
        self.lblRepAttachedOk.setText(_fromUtf8(""))
        self.lblRepAttachedOk.setObjectName(_fromUtf8("lblRepAttachedOk"))
        self.label_10 = QtGui.QLabel(emailReportRoad)
        self.label_10.setGeometry(QtCore.QRect(320, 20, 33, 31))
        self.label_10.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/email.png);"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(emailReportRoad)
        self.label_11.setGeometry(QtCore.QRect(50, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.btnGmail = QtGui.QToolButton(emailReportRoad)
        self.btnGmail.setGeometry(QtCore.QRect(320, 100, 61, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.btnGmail.setFont(font)
        self.btnGmail.setStyleSheet(_fromUtf8(""))
        self.btnGmail.setObjectName(_fromUtf8("btnGmail"))
        self.btnYahoo = QtGui.QToolButton(emailReportRoad)
        self.btnYahoo.setGeometry(QtCore.QRect(460, 100, 61, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.btnYahoo.setFont(font)
        self.btnYahoo.setStyleSheet(_fromUtf8(""))
        self.btnYahoo.setObjectName(_fromUtf8("btnYahoo"))
        self.btnHotmail = QtGui.QToolButton(emailReportRoad)
        self.btnHotmail.setGeometry(QtCore.QRect(390, 100, 61, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.btnHotmail.setFont(font)
        self.btnHotmail.setStyleSheet(_fromUtf8(""))
        self.btnHotmail.setObjectName(_fromUtf8("btnHotmail"))
        self.label_12 = QtGui.QLabel(emailReportRoad)
        self.label_12.setGeometry(QtCore.QRect(320, 510, 21, 21))
        self.label_12.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/email-send-icon1.png);"))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(emailReportRoad)
        self.label_13.setGeometry(QtCore.QRect(320, 70, 61, 51))
        self.label_13.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/Gmail-icon1.png);"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(emailReportRoad)
        self.label_14.setGeometry(QtCore.QRect(390, 70, 61, 51))
        self.label_14.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/outlook-icon1.png);"))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(emailReportRoad)
        self.label_15.setGeometry(QtCore.QRect(460, 70, 61, 51))
        self.label_15.setStyleSheet(_fromUtf8("image: url(:/plugins/floogin/Yahoo-icon1.png);"))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))

        self.retranslateUi(emailReportRoad)
        QtCore.QMetaObject.connectSlotsByName(emailReportRoad)

    def retranslateUi(self, emailReportRoad):
        emailReportRoad.setWindowTitle(_translate("emailReportRoad", "Email Generated Report", None))
        self.label.setText(_translate("emailReportRoad", "Username", None))
        self.label_2.setText(_translate("emailReportRoad", "Password", None))
        self.label_3.setText(_translate("emailReportRoad", "From", None))
        self.label_4.setText(_translate("emailReportRoad", "To", None))
        self.label_5.setText(_translate("emailReportRoad", "Subject", None))
        self.txtUsernameRep.setText(_translate("emailReportRoad", "<Type your Username here>", None))
        self.txtPasswordRep.setText(_translate("emailReportRoad", "<Type your password here>", None))
        self.txtFromRep.setText(_translate("emailReportRoad", "<Type your E-mail address here>", None))
        self.txtToRep.setText(_translate("emailReportRoad", "<Type the recipient E-mail address here>", None))
        self.txtSubjectRep.setText(_translate("emailReportRoad", "<Type a subject for your e-mail here>", None))
        self.label_6.setText(_translate("emailReportRoad", "Login details", None))
        self.label_7.setText(_translate("emailReportRoad", "Email the generated report to anyone", None))
        self.label_8.setText(_translate("emailReportRoad", "Report", None))
        self.lblReportAttached.setText(_translate("emailReportRoad", "_", None))
        self.label_9.setText(_translate("emailReportRoad", "Message details", None))
        self.btnSendEmailRoad.setToolTip(_translate("emailReportRoad", "Send email", None))
        self.btnSendEmailRoad.setText(_translate("emailReportRoad", "Send", None))
        self.btnEmailClear.setToolTip(_translate("emailReportRoad", "Clear Fields", None))
        self.btnEmailClear.setText(_translate("emailReportRoad", "Clear", None))
        self.btnEmailExit.setToolTip(_translate("emailReportRoad", "Exit", None))
        self.btnEmailExit.setText(_translate("emailReportRoad", "Exit", None))
        self.label_11.setText(_translate("emailReportRoad", "Select your Email service", None))
        self.btnGmail.setToolTip(_translate("emailReportRoad", "Gmail", None))
        self.btnGmail.setText(_translate("emailReportRoad", "Gmail", None))
        self.btnYahoo.setToolTip(_translate("emailReportRoad", "Yahoo", None))
        self.btnYahoo.setText(_translate("emailReportRoad", "Yahoo", None))
        self.btnHotmail.setToolTip(_translate("emailReportRoad", "Hotmail", None))
        self.btnHotmail.setText(_translate("emailReportRoad", "Hotmail", None))

import resources_rc
